# Generated by Django 4.2.1 on 2023-05-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
